services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      tags:
        - "romcomrater:backend-dev"
    working_dir: /workspace/backend
    entrypoint: /workspace/backend/entrypoint.sh
    command: uv run python main.py
    volumes:
      - ./:/workspace
    
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      tags:
        - "romcomrater:frontend-dev"
    working_dir: /workspace/frontend
    entrypoint: /workspace/frontend/entrypoint.sh
    command: npm install && npm run dev
    volumes:
      - ./:/workspace
