services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      tags:
        - "romcomrater:backend-dev"
    working_dir: /workspace/backend
    entrypoint: /workspace/backend/entrypoint.sh
    command: uv run python main.py
    volumes:
      - ./:/workspace
