services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      tags:
        - "romcomrater:backend-dev"
    working_dir: /workspace/backend      
    entrypoint: ["bash", "-lc"]
    command: nix develop path:/workspace -c uv run python -m backend
    volumes:
      - ./:/workspace
