services:
  backend:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      tags:
        - "romcomrater:backend-dev"
    entrypoint: ["/workspace/backend/entrypoint.sh"]
    command: ["uv", "run", "python", "main.py"]
    volumes:
      - ./:/workspace
    ports:
      - 8080:8080
    
  frontend:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      tags:
        - "romcomrater:frontend-dev"
    entrypoint: ["/workspace/frontend/entrypoint.sh"]
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/workspace
    ports:
      - 3000:3000
